# Copyright (c) 2014 - 2015 townhallpinball.org
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

MatrixLights:
    l_ball_launch_button:
        number: L86
    l_buy_extra_ball_button:
        number: L87
    l_start_button:
        number: L88
    l_circle_1:
        number: L26
    l_circle_2:
        number: L25
    l_circle_3:
        number: L24
    l_circle_4:
        number: L23
    l_circle_5:
        number: L22
    l_circle_6:
        number: L11
    l_circle_7:
        number: L12
    l_circle_8:
        number: L13
    l_circle_9:
        number: L14
    l_circle_10:
        number: L15
    l_circle_11:
        number: L16
    l_circle_12:
        number: L18
    l_circle_center:
        number: L21
    l_inlane_left:
        number: L66
    l_inlane_right:
        number: L73
    l_kickback:
        number: L68
    l_orbit_left_arrow_1:
        number: L57
    l_orbit_left_arrow_2:
        number: L51
    l_orbit_left_lamp_3:
        number: L53
    l_orbit_left_sign:
        number: L38
    l_orbit_right_arrow_1:
        number: L77
    l_orbit_right_arrow_2:
        number: L78
    l_outlane_left:
        number: L67
    l_outlane_right:
        number: L74
    l_playfield_center:
        number: L28
    l_playfield_far_left:
        number: L48
    l_playfield_far_right:
        number: L37
    l_playfield_left:
        number: L17
    l_playfield_right:
        number: L27
    l_ramp_left_arrow:
        number: L56
    l_ramp_left_circle_1:
        number: L55
    l_ramp_left_circle_2:
        number: L52
    l_ramp_left_circle_3:
        number: L54
    l_ramp_left_sign_bottom:
        number: L83
    l_ramp_left_sign_top:
        number: L84
    l_ramp_right_arrow_1:
        number: L75
    l_ramp_right_arrow_2:
        number: L76
    l_ramp_right_circle_1:
        number: L63
    l_ramp_right_circle_2:
        number: L64
    l_ramp_right_circle_3:
        number: L65
    l_scoop_left_arrow_1:
        number: L45
    l_scoop_left_arrow_2:
        number: L46
    l_scoop_left_arrow_3:
        number: L47
    l_scoop_center_arrow_1:
        number: L31
    l_scoop_center_arrow_2:
        number: L33
    l_scoop_center_arrow_3:
        number: L34
    l_scoop_center_arrow_4:
        number: L36
    l_scoop_center_circle:
        number: L35
    l_shoot_again:
        number: L81
    l_skull_eye_left:
        number: L82
    l_skull_eye_right:
        number: L85
    l_standup_target_top:
        number: L71
    l_standup_target_bottom:
        number: L72
    l_uturn_left_arrow:
        number: L41
    l_uturn_left_circle_1:
        number: L42
    l_uturn_left_ciricle_2:
        number: L43
    l_uturn_left_circle_3:
        number: L44
    l_uturn_right_arrow:
        number: L32

