# Copyright (c) 2014 - 2015 townhallpinball.org
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

Switches:
    s_ball_launch_button:
        number: S11
    s_buy_extra_ball_button:
        number: S23
    s_coin_chute_left:
        number: SD1
    s_coin_chute_center:
        number: SD2
    s_coin_chute_right:
        number: SD3
    s_coin_chute_fourth:
        number: SD4
    s_coin_door_closed:
        number: S22
    s_drop_target:
        number: S51
        tags: playfield_active
    s_flipper_button_left:
        number: SF4
    s_flipper_button_right:
        number: SF6
    #flipperRightUp: SF6
    s_kickback:
        number: S25
        tags: playfield_active
    s_magnet_left:
        number: S46
        type: NC
        tags: playfield_active
    s_magnet_center:
        number: S47
        type: NC
        tags: playfield_active
    s_magnet_right:
        number: S48
        type: NC
        tags: playfield_active
    s_orbit_left:
        number: S62
        tags: playfield_active
    s_orbit_right:
        number: S58
        tags: playfield_active
    s_outlane_right:
        number: S17
        tags: playfield_active
    s_popper:
        number: S41
        type: NC
    s_popper_next:
        number: S42
        type: NC
    s_ramp_left_enter:
        number: S63
        tags: playfield_active
    s_ramp_left_middle:
        number: S64
        tags: playfield_active
    s_ramp_right_enter:
        number: S66
        tags: playfield_active
    s_ramp_right_exit:
        number: S67
        tags: playfield_active
    s_return_left:
        number: S18
        tags: playfield_active
    s_return_right:
        number: S18
        tags: playfield_active
    s_saucer:
        number: S61
        tags: playfield_active
    s_service_down:
        number: SD6
    s_service_enter:
        number: SD8
    s_service_down:
        number: SD6
    s_service_up:
        number: SD7
    s_service_exit:
        number: SD5
    s_shooter_lane:
        number: S15
    s_slingshot_left:
        number: S27
        tags: playfield_active
    s_slingshot_right:
        number: S28
        tags: playfield_active
    s_spinner:
        number: S16
        tags: playfield_active
    s_standup_target_top:
        number: S57
        tags: playfield_active
    s_standup_target_bottom:
        number: S56
        tags: playfield_active
    s_start_button:
        number: S13
        tags: start
    s_subway_left:
        number: S38
        type: NC
        tags: playfield_active
    s_subway_center:
        number: S37
        type: NC
        tags: playfield_active
    s_tilt_plumb:
        number: S14
    s_tilt_slam:
        number: S21
    s_trough_1:
        number: S32
        type: NC
    s_trough_2:
        number: S33
        type: NC
    s_trough_3:
        number: S34
        type: NC
    s_trough_4:
        number: S35
        type: NC
    s_trough_jam:
        number: S31
        type: NC
    s_uturn:
        number: S55
        tags: playfield_active
    s_wireform_left:
        number: S54
        tags: playfield_active

