BallDevices:

    trough:
        tags: trough, home, drain
        label: Trough
        ball_switches: trough_1, trough_2, trough_3, trough_4, trough_jam
        entrance_count_delay: 0.5s
        eject_coil: trough
        confirm_eject_type: target
        eject_targets: shooter_lane
        jam_switch: trough_jam

    shooter_lane:
        tags: ball_add_live
        label: Shooter Lane
        ball_switches: shooter_lane
        entrance_count_delay: 0.3s
        eject_coil: plunger
        confirm_eject_type: playfield


