BallDevices:

    trough:
        tags: trough, home, drain
        label: Trough
        ball_switches: s_trough_1, s_trough_2, s_trough_3, s_trough_4, s_trough_jam
        entrance_count_delay: 0.5s
        eject_coil: c_trough
        confirm_eject_type: target
        eject_targets: shooter_lane
        jam_switch: s_trough_jam

    shooter_lane:
        tags: ball_add_live
        label: Shooter Lane
        ball_switches: s_shooter_lane
        entrance_count_delay: 0.3s
        eject_coil: c_plunger
        confirm_eject_type: playfield


