BallDevices:
    trough:
        ball_switches: trough1, trough2, trough3, trough4, trough5, trough6, troughJam
        entrance_count_delay: 300ms
        eject_coil: troughEject
        eject_switch: trough6
        confirm_eject_type: device
        target_device: plunger
        tags: trough, home, drain
    plunger:
        ball_switches: plungerLane
        entrance_count_delay: 300ms
        exit_count_delay: 3s
        eject_switch: plungerLane
        eject_coil: plungerEject
        confirm_eject_type: count
        tags: ball_add_live
