Coils:
    flipperLeftMain:
        number: FLLM
        pulse_ms: 20
    flipperLeftHold:
        number: FLLH
    flipperRightMain:
        number: FLRM
        pulse_ms: 20
    flipperRightHold:
        number: FLRH
    trough_eject:
        number: C13
        pulse_ms: 20
    plunger_eject:
        number: C08
        pulse_ms: 20
