# Copyright (c) 2014 - 2015 townhallpinball.org
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

Coils:
    c_drop_target_down:
        number: C08
    c_drop_target_up:
        number: C12
    c_flipper_left_main:
        number: FLLM
    c_flipper_left_hold:
        number: FLLH
    c_flipper_right_main:
        number: FLRM
    c_flipper_right_hold:
        number: FLRH
    c_flipper_right_upper_main:
        number: FURM
    c_flipper_right_upper_hold:
        number: FURH
    c_kickback:
        number: C04
    c_knocker:
        number: C07
    c_magnet_left:
        number: C06
    c_magnet_center:
        number: C05
    c_magnet_right:
        number: C03
    c_plunger:
        number: C02
    c_popper:
        number: C01
    c_saucer:
        number: C15
    c_skull_mouth:
        number: C16
    c_slingshot_left:
        number: C11
    c_slingshot_right:
        number: C10
    c_trough:
        number: C14


Autofire Coils:
    slingshot_left:
        coil: c_slingshot_left
        switch: s_slingshot_left
    slingshot_right:
        coil: c_slingshot_right
        switch: s_slingshot_right


