Plugins:
    - keyboard.Keyboard
    - sound.SoundController

Config:
    - ball_devices.yaml
    - coils.yaml
    - display.yaml
    - flashers.yaml
    - flippers.yaml
    - game.yaml
    - gi.yaml
    - images.yaml
    - keyboard.yaml
    - lamps.yaml
    - machine.yaml
    - modes.yaml
    - players.yaml
    - sound_system.yaml
    - switches.yaml
