Plugins:
    - keyboard.Keyboard
    - sound.SoundController
    - debug_dmd.DebugDMD

Config:
    - no_fear/ball_devices.yaml
    - no_fear/coils.yaml
    - no_fear/flashers.yaml
    - no_fear/flippers.yaml
    - no_fear/gi.yaml
    - no_fear/lamps.yaml
    - no_fear/machine.yaml
    - no_fear/switches.yaml
    - display.yaml
    - game.yaml
    - images.yaml
    - keyboard.yaml
    - modes.yaml
    - players.yaml
    - sound_system.yaml
