Plugins:
    - keyboard.Keyboard

Config:
    - no_fear/ball_devices.yaml
    - no_fear/coils.yaml
    - no_fear/flashers.yaml
    - no_fear/flippers.yaml
    - no_fear/lamps.yaml
    - no_fear/machine.yaml
    - no_fear/switches.yaml
    - display.yaml
    - game.yaml
    - images.yaml
    - keyboard.yaml
    - players.yaml
