# Copyright (c) 2014 - 2015 townhallpinball.org
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

DMD:
    physical: yes
    width: 128
    height: 32
    shades: 16
    fps: auto


Window:
    width: 600
    height: 450
    title: Project Alpha
    resizable: yes
    frame: yes
    fullscreen: no
    fps: auto
    quit_on_close: True
    elements:

    - type: VirtualDMD
      width: 512
      height: 128
      h_pos: center
      v_pos: center
      pixel_color: ff6600
      dark_color: 220000
      layer: 1
      pixel_spacing: 2

    - type: Text
      font: tall title
      text: Project Alpha
      h_pos: right
      v_pos: bottom
      y: -10
      x: -20
      size: 60
      antialias: yes
      layer: 1
      color: ee9900

    - type: Shape
      shape: box
      width: 516
      height: 132
      layer: 2
      thickness: 2
      v_pos: center
      h_pos: center
      color: aaaaaa

    - type: Image
      image: thp_logo
      h_pos: left
      v_pos: top
      y: 10
      x: 20



