DMD:
    physical: yes
    width: 128
    height: 32
    shades: 16
    fps: auto


Window:
    width: 600
    height: 450
    title: Project Alpha
    resizable: yes
    frame: yes
    fullscreen: no
    fps: auto
    quit_on_close: True
    elements:

    - type: VirtualDMD
      width: 512
      height: 128
      h_pos: center
      v_pos: center
      pixel_color: ff6600
      dark_color: 220000
      layer: 1
      pixel_spacing: 2

    - type: Text
      font: tall title
      text: Project Alpha
      h_pos: right
      v_pos: bottom
      y: -10
      x: -20
      size: 60
      antialias: yes
      layer: 1
      color: ee9900

    - type: Shape
      shape: box
      width: 516
      height: 132
      layer: 2
      thickness: 2
      v_pos: center
      h_pos: center
      color: aaaaaa

#    - type: Image
#      image: thp_logo
#      h_pos: left
#      v_pos: top
#      y: 10
#      x: 20



