Keyboard:
    shift-s:
        switch: s_start_button
    s:
        switch: s_saucer
        toggle: True
    l:
        switch: s_ball_launch_button
    1:
        switch: s_trough_1
    q:
        switch: s_shooter_lane
    z:
        switch: s_flipper_left_button
    x:
        switch: s_flipper_right_button

