Machine:
    HZ: 60
    Balls Installed: 4
    Min Balls: 0 # Allow game to start without any balls in the trough
    # Min Balls: 1
    Max Balls: 4

Hardware:
    Platform: p_roc
    DriverBoards: wpc

MPF:
    default_pulse_ms: 20
