# Copyright (c) 2014 - 2015 townhallpinball.org
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

ShowPlayer:
    machineflow_Attract_start:
        - show: attract
          repeat: yes
          tocks_per_sec: 1
        - show: attract_center_white_cycle
          repeat: yes
          tocks_per_sec: 5
        - show: attract_circle_cycle
          repeat: yes
          tocks_per_sec: 5
        - show: attract_lane_sweep
          repeat: yes
          tocks_per_sec: 5
        - show: attract_orbit_left_sweep
          repeat: yes
          tocks_per_sec: 5
        - show: attract_orbit_right_alternate
          repeat: yes
          tocks_per_sec: 5
        - show: attract_ramp_left_sign_alternate
          repeat: yes
          tocks_per_sec: 5
        - show: attract_ramp_left_sweep
          repeat: yes
          tocks_per_sec: 5
        - show: attract_ramp_right_circle_sweep
          repeat: yes
          tocks_per_sec: 5
        - show: attract_saucer_alternate
          repeat: yes
          tocks_per_sec: 5
        - show: attract_scoop_center_sweep
          repeat: yes
          tocks_per_sec: 5
        - show: attract_scoop_left_sweep
          repeat: yes
          tocks_per_sec: 5
        - show: attract_standup_alternate
          repeat: yes
          tocks_per_sec: 5
        - show: attract_toy_blink
          repeat: yes
          tocks_per_sec: 5
        - show: attract_uturn_left_sweep
          repeat: yes
          tocks_per_sec: 5
        - show: attract_uturn_right_blink
          repeat: yes
          tocks_per_sec: 5
    machineflow_Attract_stop:
        - show: attract
          action: stop
        - show: attract_center_white
          action: stop
        - show: attract_circle_sweep
          action: stop
        - show: attract_lane_sweep
          action: stop
        - show: attract_orbit_left
          action: stop
        - show: attract_orbit_right_alternate
          action: stop
        - show: attract_ramp_left_sign_alternate
          action: stop
        - show: attract_ramp_left_sweep
          action: stop
        - show: attract_ramp_right_circle_sweep
          action: stop
        - show: attract_saucer_alternate
          action: stop
        - show: attract_scoop_center_sweep
          action: stop
        - show: attract_scoop_left_sweep
          action: stop
        - show: attract_standup_alternate
          action: stop
        - show: attract_toy_blink
          action: stop
        - show: attract_uturn_left_sweep
          action: stop
        - show: attract_uturn_right_blink
          action: stop







